### ISSUE TITLE
menu 栏会跳转到 http 而不是 https, 而 http 找不到网页

### ISSUE THREAD

**Issue by ghost** [xuecat/xuecat.github.io#1]
[https://github.com/iissnan/hexo-theme-next/issues/1152](https://github.com/iissnan/hexo-theme-next/issues/1152) 请问楼主是如何解决这个问题的，被这问题折磨了一整天了？

**Comment by xuecat** [comment]
不用到我这开个`issues`吧。 
访问https是正常的哦，github本身就是https的域名，你上传静态网页上去默认访问的就是https。
搭建出来的博客网址访问都是https的。

你访问http或者访问无http前缀的网页，我有以下想法：
1. 你在本地测试`hexo s`后再上传时，浏览器可能做了缓存，导致访问到这种网址。(浏览器是由禁止缓存的选项的)
2. 运营商做缓存。我的例子就是这样，我的运营商对国外站点访问都做了缓存，所以导致当时搭博客时不时的抽风。

**Comment by ghost** [comment]
真的抱歉，不过今天无缘无故又可以访问了，真的很奇怪，不过还是非常感谢你！
